layout2={
  LinearLayout;
  layout_height="wrap";
  layout_width="wrap";
  {
    CardView;
    layout_height = "wrap";
    layout_width = "wrap";
    backgroundColor="transperent";--"#22000000";
    id="menu"; -- 				Layout max
    {
      LinearLayout;
      layout_height = "wrap";
      layout_width = "wrap";
      Orientation="vertical";
      {
        LinearLayout;
        orientation="horizontal";
        id="win_mainview1",
        layout_height="27dp";
        layout_width="50%w";
        background="transparent",
        {

          ImageView;
          id="img1";
          layout_width="45";
          layout_height="65";
          layout_marginLeft="7dp";
          layout_gravity="left|center";
          padding="3";
          src="ic_to_top.png";
          colorFilter="0xFF000000";
        };
        {
          TextView;
          textColor="0xFF000000";
          textSize="13.5dp";
          layout_marginLeft="10dp";
          text="DeFexInjector V1🇺🇦";
          layout_gravity="center";
          gravity="center";
          id="win_move";
        };
      };
      {
        LinearLayout;
        Orientation="vertical";
        layout_height = "220dp";
        layout_width = "93%w";
        visibility="gone";
        backgroundColor="0xFFF1F1F1";
        id="cheatMenu";
        {
          LinearLayout;
          id="";
          Orientation="vertical";
          layout_height = "fill";
          layout_width = "fill";
          layout_gravity="center";
          padding="5dp";
          {
            HorizontalScrollView;
            layout_width="320dp";
            layout_height="38dp",
            layout_gravity="center";
            id="QQ";

            {
              LinearLayout;
              layout_height="-1";
              layout_width="-1";
              orientation="horizontal";
              background="transparent";
              {
                TextView;
                text="Main";
                id="menu1",
                layout_gravity="center";
                gravity="center";
                textSize="13dp";
                textColor="0xFF000000";
                layout_height="3.4%h";
                layout_width="14%w";
              };
              {
                LinearLayout;
                layout_height=".5%h";
                layout_width="2%w";
                background="transparent",
              };
              {
                TextView;
                text="Other";
                id="menu2",
                textSize="13dp";
                layout_gravity="center";
                gravity="center";
                textColor="0xFF000000";
                background="#ff252525";
                layout_height="3.4%h";
                layout_width="20%w";
              };
              {
                LinearLayout;
                layout_height=".5%h";
                layout_width="2%w";
                background="transparent",
              };
              {
                TextView;
                text="Contacts";
                id="menu3",
                textSize="13dp";
                layout_gravity="center";
                gravity="center";
                textColor="0xFF000000";
                background="#ff252525";
                layout_height="3.4%h";
                layout_width="13%w";
              };
            };
          };

          {
            LinearLayout,
            layout_height = "1.5dp",
            layout_width = "fill",
            backgroundColor = "0xFFC5C9E4",
            layout_marginTop="-6.5dp";
            layout_marginLeft = "9dp",
            layout_marginRight = "9dp",
          },
          {
            LinearLayout;
            layout_height="0.5%h";
            layout_width="fill";
          };
          {
            PageView,
            id="pg",
            layout_width="fill",
            layout_height="fill",
            pages={
              {
                LinearLayout;
                orientation="vertical";
                padding="5";
                {
                  ScrollView;
                  layout_width="fill_parent";
                  layout_height="fill",
                  layout_gravity="center_horizontal";
                  {
                    LinearLayout;
                    layout_height="-1";
                    layout_width="-1";
                    orientation="vertical";
                    {
                      LinearLayout;
                      id="_drawer_header";
                      layout_height="-2";
                      layout_width="-1";
                      orientation="vertical";
                      {
                        LinearLayout;
                        layout_height="-1";
                        layout_width="-1";
                        orientation="vertical";
                        padding="0";
                        {
                          LinearLayout;
                          orientation="horizontal";
                          layout_height="10";
                          layout_width="-1";
                        };
                        {
                          LinearLayout;
                          orientation="horizontal";
                          layout_height="7.5%w";
                          layout_width="fill";
                          layout_gravity="center";
                          id="basic";
                          {
                            ImageView;
                            id="img2";
                            layout_width="45";
                            layout_height="65";
                            layout_marginLeft="7dp";
                            layout_gravity="left|center";
                            padding="3";
                            src="ic_to_top.png";
                            colorFilter="0xFF000000";
                          };
                          {
                            TextView;
                            textColor="0xFF000000";
                            textSize="13.5dp";
                            layout_marginLeft="10dp";
                            text="PVP Menu";
                            gravity="center";
                            layout_gravity="center";
                            id="";

                          };
                        };
                        {
                          LinearLayout;
                          layout_marginTop="7dp";
                          orientation="horizontal";
                          layout_height="wrap";
                          layout_width="wrap";

                          {
                            CheckBox;
                            text="ESP";
                            textColor="0xFF000000";
                            id="";
                            layout_gravity="center";
                            textSize="10sp";
                            layout_width="fill";
                            layout_height="wrap";

                          };
                          {
                            CheckBox;
                            text="Throught Walls";
                            textColor="0xFF000000";
                            id="notexture";
                            layout_gravity="center";
                            textSize="10sp";
                            layout_width="fill";
                            layout_height="wrap";
                          };
                          {
                            CheckBox;
                            text="NoRecoil";
                            textColor="0xFF000000";
                            id="pvp";
                            layout_gravity="center";
                            textSize="10sp";
                            layout_width="fill";
                            layout_height="wrap";
                          };
                          {
                            CheckBox;
                            text="Magic";
                            textColor="0xFF000000";
                            id="magic";
                            layout_gravity="center";
                            textSize="10sp";
                            layout_width="fill";
                            layout_height="wrap";
                          };
                          {
                            CheckBox;
                            text="10x";
                            textColor="0xFF000000";
                            id="scope";
                            layout_gravity="center";
                            textSize="10sp";
                            layout_width="fill";
                            layout_height="wrap";
                          };
                        };
                        {
                          LinearLayout;
                          orientation="horizontal";
                          layout_height="wrap";
                          layout_width="wrap";

                          {
                            CheckBox;
                            text="FastReload";
                            textColor="0xFF000000";
                            id="fastreload";
                            layout_gravity="center";
                            textSize="10sp";
                            layout_width="fill";
                            layout_height="wrap";
                          };
                          {
                            CheckBox;
                            text="DelMap";
                            textColor="0xFF000000";
                            id="nomap";
                            layout_gravity="center";
                            textSize="10sp";
                            layout_width="fill";
                            layout_height="wrap";
                          };
                          {
                            CheckBox;
                            text="Ipad";
                            textColor="0xFF000000";
                            id="ipad";
                            layout_gravity="center";
                            textSize="10sp";
                            layout_width="fill";
                            layout_height="wrap";
                          };
                          {
                            CheckBox;
                            text="Test";
                            textColor="0xFF000000";
                            id="aboba";
                            layout_gravity="center";
                            textSize="10sp";
                            layout_width="fill";
                            layout_height="wrap";
                          };
                          {
                            CheckBox;
                            text="VirtualBuild";
                            textColor="0xFF000000";
                            id="virt";
                            layout_gravity="center";
                            textSize="10sp";
                            layout_width="fill";
                            layout_height="wrap";
                          };
                        };
                        {
                          LinearLayout;
                          layout_height="0.5%h";
                          layout_width="fill";
                        };
                        {
                          LinearLayout,
                          layout_height = "1dp",
                          layout_width = "fill",
                          backgroundColor = "0xFF000000",
                        },
                        {
                          LinearLayout;
                          layout_height="0.5%h";
                          layout_width="fill";
                        };
                        {
                          LinearLayout;
                          orientation="horizontal";
                          layout_height="wrap";
                          layout_width="wrap";

                          {
                            CheckBox;
                            text="Exit";
                            textColor="0xFF000000";
                            id="exit";
                            layout_gravity="center";
                            textSize="13.5sp";
                            layout_width="fill";
                            layout_height="wrap";
                          };
                          {
                            CheckBox;
                            text="Start";
                            textColor="0xFF000000";
                            id="lox";
                            layout_gravity="center";
                            textSize="13.5sp";
                            layout_width="fill";
                            layout_height="wrap";
                          };
                        };
                        {

                          LinearLayout;
                          orientation="horizontal";
                          layout_marginTop="8dp";
                          layout_height="7.5%w";
                          layout_width="fill";
                          layout_gravity="center";
                          id="aimbot";
                          {
                            ImageView;
                            id="img3";
                            layout_width="45";
                            layout_height="65";
                            layout_marginLeft="7dp";
                            layout_gravity="left|center";
                            padding="3";
                            src="ic_to_top.png";
                            colorFilter="0xFF000000";
                          };
                          {
                            TextView;
                            textColor="0xFF000000";
                            textSize="13.5dp";
                            layout_marginLeft="10dp";
                            text="Antenna Menu";
                            gravity="center";
                            layout_gravity="center";
                            id="";
                          };
                        };
                        {
                          LinearLayout;
                          orientation="horizontal";
                          layout_height="wrap";
                          layout_width="wrap";

                          {
                            CheckBox;
                            text="Antenna";
                            textColor="0xFF000000";
                            id="antenna";
                            layout_gravity="center";
                            textSize="10sp";
                            layout_width="fill";
                            layout_height="wrap";
                          };
                          {
                            CheckBox;
                            text="Antenna Ore";
                            textColor="0xFF000000";
                            id="rudall";
                            layout_gravity="center";
                            textSize="10sp";
                            layout_width="fill";
                            layout_height="wrap";
                          };
                        };
                        {
                          LinearLayout;
                          orientation="horizontal";
                          layout_height="wrap";
                          layout_width="wrap";

                          {
                            CheckBox;
                            text="Antenna Loot Bag";
                            textColor="0xFF000000";
                            id="bag";
                            layout_gravity="center";
                            textSize="10sp";
                            layout_width="fill";
                            layout_height="wrap";
                          };
                          {
                            CheckBox;
                            text="Antenna Bed";
                            textColor="0xFF000000";
                            id="spalka";
                            layout_gravity="center";
                            textSize="10sp";
                            layout_width="fill";
                            layout_height="wrap";
                          };
                        };
                        {
                          LinearLayout;
                          orientation="horizontal";
                          layout_height="wrap";
                          layout_width="wrap";
                          layout_marginTop="7dp";

                          {
                            TextView;
                            text="0";
                            id="fire",
                            textSize="10dp";
                            layout_gravity="center";
                            gravity="center";
                            textColor="0xFF000000";
                            layout_height="3.4%h";
                            layout_width="26%w";
                          };
                          {
                            LinearLayout;
                            layout_height=".5%h";
                            layout_width="2%w";
                            background="transparent",
                          };
                          {
                            TextView;
                            text="0";
                            id="save",
                            textSize="10dp";
                            layout_gravity="center";
                            gravity="center";
                            textColor="0xFF000000";
                            layout_height="3.4%h";
                            layout_width="20%w";

                          };
                        };
                      };
                    };
                  };
                };
              };
              {
                LinearLayout;
                orientation="vertical";
                padding="5";
                {
                  ScrollView;
                  layout_width="fill_parent";
                  layout_height="fill",
                  layout_gravity="center_horizontal";
                  {
                    LinearLayout;
                    layout_height="-1";
                    layout_width="-1";
                    orientation="vertical";
                    {
                      LinearLayout;
                      id="_drawer_header";
                      layout_height="-2";
                      layout_width="-1";
                      orientation="vertical";
                      {
                        LinearLayout;
                        layout_height="-1";
                        layout_width="-1";
                        orientation="vertical";
                        padding="0";
                        {
                          LinearLayout;
                          orientation="horizontal";
                          layout_height="10";
                          layout_width="-1";
                        };
                        {
                          LinearLayout;
                          orientation="horizontal";
                          layout_height="wrap";
                          layout_width="wrap";

                          {
                            CheckBox;
                            text="Initialize ESP";
                            textColor="0xFF000000";
                            id="绘制";
                            layout_gravity="center";
                            textSize="13.5sp";
                            layout_width="fill";
                            layout_height="wrap";
                          };
                        };
                        {
                          LinearLayout;
                          orientation="horizontal";
                          layout_height="wrap";
                          layout_width="wrap";

                          {
                            CheckBox;
                            text="1";
                            textColor="0xFF000000";
                            id="方框";
                            layout_gravity="center";
                            textSize="13.5sp";
                            layout_width="fill";
                            layout_height="wrap";
                          };
                          {
                            CheckBox;
                            text="2";
                            textColor="0xFF000000";
                            id="射线";
                            layout_gravity="center";
                            textSize="13.5sp";
                            layout_width="fill";
                            layout_height="wrap";
                          };
                        };
                        {
                          LinearLayout;
                          orientation="horizontal";
                          layout_height="wrap";
                          layout_width="wrap";

                          {
                            CheckBox;
                            text="3";
                            textColor="0xFF000000";
                            id="信息";
                            layout_gravity="center";
                            textSize="13.5sp";
                            layout_width="fill";
                            layout_height="wrap";
                          };
                          {
                            CheckBox;
                            text="4";
                            textColor="0xFF000000";
                            id="背敌";
                            layout_gravity="center";
                            textSize="13.5sp";
                            layout_width="fill";
                            layout_height="wrap";
                          };
                        };
                        {
                          LinearLayout;
                          orientation="horizontal";
                          layout_height="wrap";
                          layout_width="wrap";
                          {
                            SeekBar;
                            layout_width="150sp";
                            id="调整度";
                          };
                        };
                        {
                          LinearLayout;
                          orientation="horizontal";
                          layout_marginTop="8dp";
                          layout_height="7.5%w";
                          layout_width="fill";
                          layout_gravity="center";
                          id="sniper";
                          {
                            ImageView;
                            id="img4";
                            layout_width="45";
                            layout_height="65";
                            layout_marginLeft="7dp";
                            layout_gravity="left|center";
                            padding="3";
                            src="ic_to_top.png";
                            colorFilter="0xFF000000";
                          };
                          {
                            TextView;
                            textColor="0xFF000000";
                            textSize="13.5dp";
                            layout_marginLeft="10dp";
                            text="ESP Functions";
                            gravity="center";
                            layout_gravity="center";
                            id="";
                          };
                        };
                        {

                          LinearLayout;
                          orientation="horizontal";
                          layout_height="wrap";
                          layout_width="wrap";

                          {
                            CheckBox;
                            text="3";
                            textColor="0xFF000000";
                            id="信息";
                            layout_gravity="center";
                            textSize="13.5sp";
                            layout_width="fill";
                            layout_height="wrap";
                          };
                          {
                            CheckBox;
                            text="4";
                            textColor="0xFF000000";
                            id="背敌";
                            layout_gravity="center";
                            textSize="13.5sp";
                            layout_width="fill";
                            layout_height="wrap";
                          };
                          {
                            CheckBox;
                            text="2";
                            textColor="0xFF000000";
                            id="射线";
                            layout_gravity="center";
                            textSize="13.5sp";
                            layout_width="fill";
                            layout_height="wrap";
                          };
                          {
                            CheckBox;
                            text="Mini14";
                            textColor="0xFF000000";
                            id="r1895";
                            layout_gravity="center";
                            textSize="13.5sp";
                            layout_width="fill";
                            layout_height="wrap";
                          };
                          {
                            CheckBox;
                            text="Win94";
                            textColor="0xFF000000";
                            id="test";
                            layout_gravity="center";
                            textSize="13.5sp";
                            layout_width="fill";
                            layout_height="wrap";
                          };
                        };
                        {
                          LinearLayout;
                          orientation="horizontal";
                          layout_marginTop="8dp";
                          layout_height="7.5%w";
                          layout_width="fill";
                          layout_gravity="center";
                          id="attachments";
                          {
                            ImageView;
                            id="img5";
                            layout_width="45";
                            layout_height="65";
                            layout_marginLeft="7dp";
                            layout_gravity="left|center";
                            padding="3";
                            src="ic_to_top.png";
                            colorFilter="0xFF000000";
                          };
                          {
                            TextView;
                            textColor="0xFF000000";
                            textSize="13.5dp";
                            layout_marginLeft="10dp";
                            text="Attachments";
                            gravity="center";
                            layout_gravity="center";
                            id="";
                          };
                        };
                        {
                          LinearLayout;
                          orientation="horizontal";
                          layout_height="wrap";
                          layout_width="wrap";

                          {
                            CheckBox;
                            text="3X";
                            textColor="0xFF000000";
                            id="sawed";
                            layout_gravity="center";
                            textSize="13.5sp";
                            layout_width="fill";
                            layout_height="wrap";
                          };
                          {
                            CheckBox;
                            text="4X";
                            textColor="0xFF000000";
                            id="r1895";
                            layout_gravity="center";
                            textSize="13.5sp";
                            layout_width="fill";
                            layout_height="wrap";
                          };
                          {
                            CheckBox;
                            text="6X";
                            textColor="0xFF000000";
                            id="r1895";
                            layout_gravity="center";
                            textSize="13.5sp";
                            layout_width="fill";
                            layout_height="wrap";
                          };
                          {
                            CheckBox;
                            text="8X";
                            textColor="0xFF000000";
                            id="r1895";
                            layout_gravity="center";
                            textSize="13.5sp";
                            layout_width="fill";
                            layout_height="wrap";
                          };
                          {
                            CheckBox;
                            text="Red Dot";
                            textColor="0xFF000000";
                            id="r1895";
                            layout_gravity="center";
                            textSize="13.5sp";
                            layout_width="fill";
                            layout_height="wrap";
                          };
                        };
                        {
                          LinearLayout;
                          orientation="horizontal";
                          layout_height="wrap";
                          layout_width="wrap";

                          {
                            CheckBox;
                            text="Mag";
                            textColor="0xFF000000";
                            id="sawed";
                            layout_gravity="center";
                            textSize="13.5sp";
                            layout_width="fill";
                            layout_height="wrap";
                          };
                          {
                            CheckBox;
                            text="Silencer";
                            textColor="0xFF000000";
                            id="r1895";
                            layout_gravity="center";
                            textSize="13.5sp";
                            layout_width="fill";
                            layout_height="wrap";
                          };
                          {
                            CheckBox;
                            text="Grenade";
                            textColor="0xFF000000";
                            id="r1895";
                            layout_gravity="center";
                            textSize="13.5sp";
                            layout_width="fill";
                            layout_height="wrap";
                          };
                        };
                        {
                          LinearLayout;
                          orientation="horizontal";
                          layout_height="wrap";
                          layout_width="wrap";
                          layout_marginTop="7dp";

                          {
                            TextView;
                            text="Save Setting";
                            id="savee",
                            textSize="13.5dp";
                            layout_gravity="center";
                            gravity="center";
                            textColor="0xFF000000";
                            layout_height="3.4%h";
                            layout_width="20%w";
                          };
                        };
                        {
                          LinearLayout;
                          layout_height="0.8%h";
                          layout_width="fill";
                        };
                        {
                          LinearLayout,
                          layout_height = "1dp",
                          layout_width = "fill",
                          backgroundColor = "0xFF000000",
                        },
                        {
                          LinearLayout;
                          layout_height="0.8%h";
                          layout_width="fill";
                        };
                        {
                          LinearLayout;
                          orientation="horizontal";
                          layout_height="wrap";
                          layout_width="wrap";

                          {
                            TextView;
                            text="Logout Account";
                            id="log",
                            textSize="13.5dp";
                            layout_gravity="center";
                            gravity="center";
                            textColor="0xFF000000";
                            layout_height="3.4%h";
                            layout_width="26%w";
                          };
                          {
                            LinearLayout;
                            layout_height=".5%h";
                            layout_width="2%w";
                            background="transparent",
                          };
                          {
                            TextView;
                            text="Restore PUBGM";
                            id="res",
                            textSize="13.5dp";
                            layout_gravity="center";
                            gravity="center";
                            textColor="0xFF000000";
                            layout_height="3.4%h";
                            layout_width="26%w";
                          };
                          {
                            LinearLayout;
                            layout_height=".5%h";
                            layout_width="2%w";
                            background="transparent",
                          };
                          {
                            TextView;
                            text="Fix Device Ban";
                            id="fix",
                            textSize="13.5dp";
                            layout_gravity="center";
                            gravity="center";
                            textColor="0xFF000000";
                            layout_height="3.4%h";
                            layout_width="26%w";
                          };
                        };
                      };
                    };
                  };
                };
              };
              {
                LinearLayout;
                orientation="vertical";
                padding="5";
                {
                  ScrollView;
                  layout_width="fill_parent";
                  layout_height="fill",
                  layout_gravity="center_horizontal";
                  {
                    LinearLayout;
                    layout_height="-1";
                    layout_width="-1";
                    orientation="vertical";
                    {
                      LinearLayout;
                      id="_drawer_header";
                      layout_height="-2";
                      layout_width="-1";
                      orientation="vertical";
                      {
                        LinearLayout;
                        layout_height="-1";
                        layout_width="-1";
                        orientation="vertical";
                        padding="0";
                        {
                          LinearLayout;
                          orientation="horizontal";
                          layout_height="10";
                          layout_width="-1";
                        };
                        {
                          TextView;
                          text="Telegram @DeFexHacks";
                          id="delet";
                          layout_gravity="center";
                          gravity="center";
                          textColor="0xFF000000";
                          layout_width="85%w";




                        };
                      };
                    };
                  };
                };
              };
            };
          };
        };
      };
    };
  };
};



